[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "WebRTC Prototype"
authors = [{name = "Kevin Liu", email = "kevliu.dev@gmail.com"}]
dynamic = ["version", "description"]
